ГРНТИ таблица и фикс всех xlsx
regiri/subd pull request #14
Opened 2024-10-28 14:57 UTC by EngoyanSY

2024-10-29 13:45 UTC, regiri approved these changes

2024-10-29 13:45 UTC, regiri commented on .gitignore
> +DB/Сводная таблица.docx
надо все .docs игнорить, ибо пользователь переназвать отчет может

2024-10-29 13:45 UTC, regiri commented on data/Сводная таблица.docx
в игнор

2024-10-29 13:45 UTC, regiri commented on models.py
> +        os.mkdir("DB")
это правильно сделано, паттерн называется цепочка проверок

2024-10-29 14:59 UTC, EngoyanSY commented
Можно добавить всю папку DB в игнор. Пока папка не в игноре, но все *.sqlite и *.docx игнорятся

2024-11-02 11:45 UTC, regiri requested changes

2024-11-02 11:45 UTC, regiri commented on .gitignore
> +DB/*.docx
вот тут, если кто-то создаст файл в корне где-то, то он в гит попадет, надо просто тогда *.docs

2024-11-02 11:45 UTC, regiri commented on adapter.py
я ждал этого четыре... нет... пять тысяч лет....

2024-11-02 11:45 UTC, regiri commented on schema.py
> +class Nir_VUZ(BaseSchema):
а что вернет валидатор поля "grnti_code" в этой таблице? спойлер: ничего не вернет, поля нет. Идея сделать базовый класс схемы хорошая, но реализована не очень правильно. Тебе нужно сделать базовый класс для всех pydantic моделей, а затем от него отнаследовать класс, который будет реализовывать валидатор "grnti_code". И тогда этот валидатор будет только там где надо

2024-11-02 11:45 UTC, regiri commented on schema.py
> +class Nir_VUZ(BaseSchema):
второй вариант - можно реализовать специальное поле в которое вшить этот валидатор. Тогда валидатор будет привязан не к классу таблицы, а к классу поля, и ты сможешь просто поле объявить в нужном тебе классе

2024-11-02 12:35 UTC, EngoyanSY commented on adapter.py
Прости, мне было морально тяжело

2024-11-02 12:40 UTC, merged